baseurl = "/"
languageCode = "en-us"
title = "Official website of Masudul Haque"
theme = "helix"
disqusShortname = "saadixl"
preserveTaxonomyNames = true

[[menu.main]]
name = "About"
url = "/#about"
weight = 1

[[menu.main]]
name = "Career"
url = "/#career"
weight = 2

[[menu.main]]
name = "Travel Stories"
url = "/travel-stories"
weight = 3

[[menu.main]]
name = "Memoirs"
url = "/memoirs"
weight = 4

[[menu.main]]
name = "Contact"
url = "/#contact"
weight = 5

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[params]
contactEmail = "saadixl-at-outlook-dot-com"
